gravityPF	=	150		;80 ;(10*ametre)/framespersec

car1_accel	=	1000	400		120
car1_boost	=	3000	750		720
car1_brake	=	2400
car1_maxgear	=	4
car1_mingear	=	-1
car1_boosttime	=	50
car1_boostmin	=	10

road_friction		=	32767
offroad_friction	=	8192

comp_road_friction	=	16384
comp_offroad_friction	=	16384

wheel_friction		=	180/2
freewheel_friction	=	1080/2

twist_friction		=	8192
twist_time		=	32

front_maxgrip		=	500
rear_maxgrip		=	500


car1_squishy_rate	=	100
car1_squishy_max	=	784
car1_squishy_anim_scale	=	65536/(car1_squishy_max/7)
car1_suck_max		=	7

car1_xanim_scale	=	8190

car1_anim_norm		=	7
car1_anim_normframe	=	4
car1_zanim		=	16
car1_zanim_max		=	256
car1_zanim_scale	=	32768/(car1_zanim_max/8)

