	defalx	stratptr,3		; ptr to strategy routine
	defalx	immuneptr,2		; ptr. to immunity object
	defalx	collobjptr,2		; ptr to collision object
	defalx	sflags,1		; strategy flags.
	defalx	sflags2,1		; strategy flags.
	defalx	sflags3,1		; strategy flags.
	defalx	sflags4,1		; strategy flags.
	defalx	sword1,2
	defalx	sword2,2
	defalx	HP,1
	defalx	AP,1
	defalx	weapontype,2
	defalx	vx,2
	defalx	vy,2
	defalx	vz,2
	defalx	shadowobj,2

;	defalx	sWPx1,2
;	defalx	sWPy1,2
;	defalx	sWPz1,2
	defalx	expstratptr,3	; ptr to explosion strategy routine
	defalx	collstratptr,3	; ptr to collision strategy routine
	defalx	Endcollstratptr,3	; ptr to end collision strategy routine
	defalx	tempstratptr,3
	defalx	stratstate,1	; 
;	defalx	fireobjptr,2
	defalx	depthoffset,2
;	defalx	relposx,1	; CAN REMOVE THIS IF NEEDS BE
;	defalx	relposy,1	; CAN REMOVE THIS IF NEEDS BE
;	defalx	relposz,1	; CAN REMOVE THIS IF NEEDS BE

	defalx	expposx,2
	defalx	expposy,2
	defalx	expposz,2
	defalx	exppos2x,1
	defalx	exppos2y,1
	defalx	exppos2z,1

	defalx	expcount,2
	defalx	expshape,2

	defalx	livesleft,2

	defalx	sbyte1,1
	defalx	sbyte2,1
	defalx	sbyte3,1
	defalx	sbyte4,1

	defalx	lapcnt,1
	defalx	enginesnd,1

	defalx	offroadtime,1
	
	defalx	lastz,2

	defalx	mapptr,2
	defalx	mapcnt,2
	defalx	mapobjid,2
	defalx	whocanseeme,2

	defalx	viewpt,2
	defalx	viewpostab,2

	defalx	viewrotx,2
	defalx	sector,2

	defalx	eyesize,1
	defalx	eyerot,1
	defalx	boostobj,2




