	structure	al_size
	defal	stratptr,3		; ptr to strategy routine
	defal	immuneptr,2		; ptr. to immunity object
	defal	collobjptr,2		; ptr to collision object
	defal	sflags,1		; strategy flags.
	defal	sflags2,1		; strategy flags.
	defal	sflags3,1		; strategy flags.
	defal	sflags4,1		; strategy flags.
	defal	sword1,2
	defal	sword2,2
	defal	HP,1
	defal	AP,1
	defal	weapontype,2
	defal	vx,2
	defal	vy,2
	defal	vz,2
	defal	shadowobj,2

